In [2]:
#清洗文本
text_data = ['   Interrobang. By Aishwarya Henriette',
            'Parking And Going. By Karl Gautier',
            '    Today Is The night. By Jarek Prakash']

[string.strip() for string in text_data]

['Interrobang. By Aishwarya Henriette',
 'Parking And Going. By Karl Gautier',
 'Today Is The night. By Jarek Prakash']

In [3]:
# 删除句号点
remove_periods = [string.replace(".", "") for string in text_data]
remove_periods

['   Interrobang By Aishwarya Henriette',
 'Parking And Going By Karl Gautier',
 '    Today Is The night By Jarek Prakash']

In [4]:
# 创建函数
def capitalizer(string: str) -> str:
    return string.upper()

[capitalizer(string) for string in text_data]

['   INTERROBANG. BY AISHWARYA HENRIETTE',
 'PARKING AND GOING. BY KARL GAUTIER',
 '    TODAY IS THE NIGHT. BY JAREK PRAKASH']

In [1]:
from bs4 import BeautifulSoup

html = '''
    <div class='full_name'><span style='font-weight:bold'>
    Masego Azra
'''

soup = BeautifulSoup(html, 'lxml')

soup.find('div', {'class': 'full_name'}).text

'\n    Masego Azra\n'

In [3]:
# 移除标点
import unicodedata
import sys

# 创建文本
text_data = ['Hi!!!! I . Love This. Song.....',
            '10000% Agree!!! #LoveIT',
            'Right?!?!']

# 创建一个标点字典
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
                           if unicodedata.category(chr(i)).startswith('P'))
[string.translate(punctuation) for string in text_data]

['Hi I  Love This Song', '10000 Agree LoveIT', 'Right']

In [1]:
# 词袋
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# 创建文本
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])
# 创建一个词袋矩阵
count = CountVectorizer()

bag_of_words = count.fit_transform(text_data)

bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [2]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [4]:
count.get_feature_names()

['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love', 'sweden']

In [6]:
# 用特定的参数创建矩阵

# ngram_range n元模型     vocabulary ：将观察值限定
count_2gram = CountVectorizer(ngram_range=(1,2),
                             stop_words='english',vocabulary=['brazil'])

bag = count_2gram.fit_transform(text_data)

bag.toarray()

array([[2],
       [0],
       [0]], dtype=int64)

In [7]:
count_2gram.get_feature_names()

['brazil']

In [8]:
count_2gram.vocabulary_

{'brazil': 0}

In [11]:
#按照单词的重要性加权
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

tfidf = TfidfVectorizer()
feature_martix = tfidf.fit_transform(text_data)

# 创建TF-IDF矩阵
feature_martix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [12]:
feature_martix.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.89442719,  0.        ,
         0.        ,  0.4472136 ,  0.        ],
       [ 0.        ,  0.57735027,  0.        ,  0.        ,  0.        ,
         0.57735027,  0.        ,  0.57735027],
       [ 0.57735027,  0.        ,  0.57735027,  0.        ,  0.57735027,
         0.        ,  0.        ,  0.        ]])

In [13]:
tfidf.get_feature_names()

['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love', 'sweden']