In [1]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [2]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [5]:
matrix[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix[:2,0:2]

array([[1, 2],
       [4, 5]])

In [8]:
# 展示一个矩阵的属性

In [9]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [11]:
# 查看行列数
matrix.shape

(3, 4)

In [12]:
# 元素的数量
matrix.size

12

In [13]:
# 查看维度
matrix.ndim

2

In [14]:
# 对多个元素同时进行某个操作
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 创建函数
add_100 = lambda i:i + 100
# 创建向量化函数
np_add_100 = np.vectorize(add_100)

# 应用
np_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [17]:
# 简单化操作
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [19]:
# 找到最大值与最小值
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("最大值", np.max(matrix))
print("最小值", np.min(matrix))

最大值 9
最小值 1


In [21]:
# 寻找列行方向上最大值与最小值

# 每一列最大值
np.max(matrix, axis=0)

array([7, 8, 9])

In [22]:
# 每一行的最大值
np.max(matrix, axis=1)

array([3, 6, 9])

In [25]:
# 计算平均值， 方差， 标准差

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 平均值
print("平均值", np.mean(matrix))
# 方差
print("方差值", np.var(matrix))
# 标准差
print("标准差", np.std(matrix))


平均值 5.0
方差值 6.666666666666667
标准差 2.581988897471611


In [26]:
# 求每一列的平均值

print("列平均值", np.mean(matrix, axis=0))


列平均值 [4. 5. 6.]


In [27]:
# 矩阵变形

# 3*4
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# 将该矩阵变为 2* 6
matrix.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
# 转置向量或矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 转置矩阵
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
# 向量是不能被转置的
np.array([0,1,2,3,4]).T

array([0, 1, 2, 3, 4])

In [31]:
# 将向量定性为行或者列才能转置
np.array([[0,1,2,3,4]]).T

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
# 展开一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 展开矩阵  
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 展开矩阵  第二种
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
# 计算矩阵的秩
np.array([[1, 1, 1],
         [1, 1, 10],
         [1, 1, 15]])
np.linalg.matrix_rank(matrix)

2

In [35]:
#计算行列式
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.linalg.det(matrix)

0.0

In [36]:
# 获取矩阵的对角线元素
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.diagonal()

array([1, 5, 9])

In [37]:
# 使用 offset 进行偏移
# 主对角线向上偏移 1 
matrix.diagonal(offset=1)

array([2, 6])

In [38]:
# 使用 offset 进行偏移
# 主对角线向下偏移 1 
matrix.diagonal(offset= -1)

array([4, 8])

In [39]:
# 矩阵的迹  对角线之和
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.trace()

15

In [40]:
# 计算特征值与特征向量
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# 查看特征值
print(eigenvalues)
# 特征向量
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [41]:
# 计算点集
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# 计算点集
np.dot(vector_a, vector_b)


32

In [42]:
# 计算点集
vector_a @ vector_b

32

In [43]:
# 矩阵的相加或者相减
matrix_a = np.array([[1, 1, 1],
                   [1, 1, 1],
                   [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                   [1, 3, 1],
                   [1, 3, 8]])

# 矩阵相加
print("矩阵相加", np.add(matrix_a, matrix_b))

# 矩阵相减
print("矩阵相减", np.subtract(matrix_a, matrix_b))

矩阵相加 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
矩阵相减 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [44]:
# 矩阵相加
print("矩阵相加", matrix_a + matrix_b)

# 矩阵相减
print("矩阵相减", matrix_a - matrix_b)

矩阵相加 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
矩阵相减 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [45]:
# 矩阵乘法
matrix_a = np.array([[1,1],
                    [1,2]])
matrix_b = np.array([[1,3],
                    [1,2]])

# 矩阵相乘
np.dot(matrix_a, matrix_b)


array([[2, 5],
       [3, 7]])

In [47]:
# 计算矩阵的逆
matrix = np.array([[1,4],
                  [2,5]])

# 计算一个矩阵的逆
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [48]:
# 生成随机数

# 设置随机数种子
np.random.seed(0)

# 生成3个0.0 到 1.0 之间的随机浮点数
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])